require "user.core.launch"
require "user.core.options"
require "user.core.keymaps"
require "user.core.autocmds"

spec "user.plugins.alpha"
spec "user.plugins.oil"
-- spec "user.plugins.flash"
spec "user.plugins.conform"
-- spec "user.plugins.primer-dark"
-- spec "user.plugins.fzf"
-- spec "user.plugins.wilder"
-- spec "user.plugins.code-dark"
spec "user.plugins.arctic"
-- spec "user.plugins.oxocarbon"
spec "user.plugins.dressing"
spec "user.plugins.navic"
spec "user.plugins.illuminate"
spec "user.plugins.cmp"
spec "user.plugins.copilot"
spec "user.plugins.lspconfig"
-- spec "user.plugins.nvimtree"
spec "user.plugins.neotree"
spec "user.plugins.telescope"
-- spec "user.plugins.telescope-tabs"
spec "user.plugins.luasnip"
spec "user.plugins.indent"
spec "user.plugins.tmux"
spec "user.plugins.treesitter"
spec "user.plugins.lspkind"
spec "user.plugins.neotest"
-- spec "user.plugins.surround"
spec "user.plugins.auto-pairs"
spec "user.plugins.devicons"
spec "user.plugins.gitsings"
spec "user.plugins.lualine"
spec "user.plugins.which-key"
-- spec "user.plugins.scrollbar"
spec "user.plugins.git"
spec "user.plugins.fugitive"
spec "user.plugins.bufferline"
spec "user.plugins.schemastore"
spec "user.plugins.ts-tools"
spec "user.plugins.mason"
spec "user.plugins.comment"
spec "user.plugins.toggleterm"
spec "user.plugins.diffview"
spec "user.plugins.harpoon"
spec "user.plugins.bfdelete"
spec "user.plugins.fidget"
spec "user.plugins.rust-tools"
spec "user.plugins.breadcrumbs"
spec "user.plugins.gp"
-- spec "user.plugins.github-theme"

require "user.core.lazy"
